### ISSUE TITLE
Extra implementaties in backend

### ISSUE THREAD

**Issue by LGDTimtou** [SELab-2/UGent-4#126]
```[tasklist]
### Tasks
- [x] gepinde_vakken aan studenten toevoegen
- [x] extra_deadline checken
- [x] PATCH toevoegen
- [x] files kunnen downloaden
- [x] api documentatie updaten
```
