### ISSUE TITLE
Werk backend

### ISSUE THREAD

**Issue by LGDTimtou** [SELab-2/UGent-4#179]
```[tasklist]
### Tasks
- [x] jaartal toevoegen aan vak
- [x] gearchiveerd toevoegen aan vak
- [x] query op gearchiveerde vakken
- [x] wiki updaten
- [x] data in databank cleanen
- [x] invitation link
```
