### ISSUE TITLE
Meer validatiechecks

### ISSUE THREAD

**Issue by LGDTimtou** [SELab-2/UGent-4#71]
Extra validatie testen

```[tasklist]
### Tasks
- [x] Als groep wordt aangemaakt moet elke student in de groep ook in het vak van het project zitten.
- [x] Als gebruiker lesgever wordt gemaakt moet gecheckt worden dat hij nergens nog student is
- [x] validatie ook toevoegen aan api documentatie
```
