### ISSUE TITLE
Extra velden toevoegen in backend

### ISSUE THREAD

**Issue by LGDTimtou** [SELab-2/UGent-4#74]
```[tasklist]
### Tasks
- [x] extra_deadline toevoegen aan project
- [x] status toevoegen aan indiening
- [x] ook api documentatie updaten
- [x] gearchiveerd en zichtbaarheid toevoegen aan project
- [x] Als project niet zichtbaar is mag de gebruiker deze ook niet kunnen zien bij GET request zonder lesgever te zijn
```
