### ISSUE TITLE
Integratie api en frontend

### ISSUE THREAD

**Issue by sPAICEcake** [SELab-2/UGent-4#86]
Mbv axios de api gebruiken voor data op te halen
```[tasklist]
### Tasks
- [x] mainpage
- [x] courseview/archivedview
- [x] aanpassen aanmaken projecten
- [x] project bekijken student/leerkracht
- [x] groepen bewerken
- [x] login
- [x] scores aanpassen
- [x] vakken leerkracht/ leerling
- [ ] vak aanmaken/ bewerken
- [x] indiening bekijken
```
